### ISSUE TITLE
设备状态中，设备ip显示不正确

### ISSUE THREAD

**Issue by heartache1987** [wificoin-project/wificoin-wifidog-auth-server#5]
操作步骤：
    1、点击设备管理；
    2、点击设备状态；
    3、查看设备ip。

预期结果：
     设备ip显示正确。
实际结果：
    设备ip显示错误。
![_20180817142731](https://user-images.githubusercontent.com/24308203/44251080-b4793000-a229-11e8-8325-e84d79b43c9a.png)

**Comment by caizhibang** [comment]
已修改，由显示ipv6地址变为显示ipv4地址。
