### ISSUE TITLE
设备状态中，设备最近上线时间显示不正确

### ISSUE THREAD

**Issue by heartache1987** [wificoin-project/wificoin-wifidog-auth-server#6]
操作步骤：
    1、点击设备管理；
    2、点击设备状态；
    3、查看设备最近上线时间。

预期结果：
    最近上线时间显示正确。
时间结果：
    最近上线时间显示错误。
![1](https://user-images.githubusercontent.com/24308203/44251245-4d0fb000-a22a-11e8-956a-2ab8825209d1.png)

**Comment by caizhibang** [comment]
已修改，最近上线时间是最近更新的时间，每次更新变更这个时间。
