### ISSUE TITLE
设备状态详情列表中，通过认证时间与最近访问时间显示错误

### ISSUE THREAD

**Issue by heartache1987** [wificoin-project/wificoin-wifidog-auth-server#7]
操作步骤：
    1、点击设备管理；
    2、点击设备状态；
    3、点击详情；
    4、查看通过认证时间与最近访问时间。
预期结果：
     时间显示正确。
实际结果：
    时间显示错误。
![2](https://user-images.githubusercontent.com/24308203/44251948-e9d34d00-a22c-11e8-96ce-767689f58747.png)

**Comment by caizhibang** [comment]
已修改
