### ISSUE TITLE
子账号下设备状态详细中基本信息中获取不到数据

### ISSUE THREAD

**Issue by heartache1987** [wificoin-project/wificoin-wifidog-auth-server#9]
操作步骤：
    1、登陆子账号；
    2、点击设备管理；
    3、点击设备状态；
    4、点击详情；
    5、查看基本信息。
预期结果：
     基本信息列表中显示设备信息。
实际结果：
    基本信息列表中显示暂无数据。
![2](https://user-images.githubusercontent.com/24308203/44318574-7e29f380-a469-11e8-8f57-204740c30b59.png)

**Comment by caizhibang** [comment]
已修改，更改过滤字段，使得能够获取到数据。
